name: Auto Commit

on:
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Auto Commits
        run: |
          git config --global user.name "kakulaxxx"
          git config --global user.email "your-email@example.com"
          for i in {5..18}; do
            echo "Dòng $i" >> README.md
            git add README.md
            git commit -m "Add line $i to README"
          done
          git push
